FROM hub.i.basemind.com/stepmind/baseimage/pytorch:2.5.1-cuda12.1

WORKDIR /workspace

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" \
    && bash Miniforge3-$(uname)-$(uname -m).sh -b -p /data/miniforge3 \
    && /data/miniforge3/bin/conda init bash \
    && rm Miniforge3-$(uname)-$(uname -m).sh
ENV PATH="/data/miniforge3/bin:$PATH"

COPY environment.yml .

RUN conda env create -f environment.yml

SHELL ["/bin/bash", "-c"]

RUN source /data/miniforge3/etc/profile.d/conda.sh \
    && conda activate f5-tts \
    && conda install -c conda-forge montreal-forced-aligner \
    && mfa model download acoustic mandarin_mfa \
    && mfa model download dictionary mandarin_china_mfa